version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:80"
    networks:
      - internal_net
      - web_net

  backend:
    build: ./api
    container_name: backend
    expose:
      - "5000"
    networks:
      - internal_net

networks:
  internal_net:
  web_net:
